name: GitHub Actions Demo
on: 
  push:
    branches: 
      - master
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo "Hello World from testing job"
       
       
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hallo Message
        run: echo "Hello World from deploy job"
    
